# Generated by Django 6.1.1 on 2026-09-07 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_per_page', models.PositiveSmallIntegerField(default=15, help_text='Rows shown per page in every module table (5-100).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('public_site_enabled', models.BooleanField(default=True, help_text='When switched off, the public pages show a maintenance notice. Staff sign-in and the internal system are unaffected.', verbose_name='Public website available')),
                ('notice_message', models.CharField(blank=True, help_text='Shown as a banner to every signed-in user, for example during scheduled maintenance. Leave empty for no banner.', max_length=255, verbose_name='System notice')),
                ('notice_level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('danger', 'Urgent')], default='info', max_length=10)),
                ('session_notice_minutes', models.PositiveSmallIntegerField(default=5, help_text='Minutes before session expiry that a warning is shown (1-60).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Session warning')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system settings',
                'verbose_name_plural': 'system settings',
            },
        ),
    ]
