# Generated by Django 6.1.1 on 2026-09-07 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Local Government Monitoring and Evaluation Division', max_length=200, verbose_name='homepage heading')),
                ('hero_lead', models.TextField(default='The Division oversees the performance of local government units across Caraga - monitoring compliance with national policy, evaluating programs and projects, and publishing the results for public scrutiny.', help_text='The paragraph under the homepage heading.', verbose_name='homepage introduction')),
                ('mandate_intro', models.CharField(default='LGMED carries out three interlocking functions on behalf of the Regional Office.', help_text='The line above the three function cards on the homepage.', max_length=255, verbose_name='mandate introduction')),
                ('about_intro', models.TextField(default='The Local Government Monitoring and Evaluation Division is one of the operating divisions of the Department of the Interior and Local Government Regional Office XIII - Caraga. It is responsible for monitoring and evaluating the performance of local government units in the region, and for reporting the results to regional management, to the national office and to the public.', verbose_name='about the Division')),
                ('core_functions', models.TextField(default="Monitoring the compliance of local government units with national laws, policies and issuances.\nEvaluating the implementation and results of local governance programs and projects.\nConducting field validation and assessment activities across the region's provinces, cities and municipalities.\nMaintaining the regional record of monitoring findings, recommendations and follow-up actions.\nPreparing and publishing monitoring and evaluation reports.\nProviding technical assistance and frontline services to local government units.", help_text='One function per line. Shown as the list on the About page.', verbose_name='core functions')),
                ('address', models.CharField(default='Purok 1-A, Brgy. Doongan, Butuan City, 8600', max_length=255, verbose_name='office address')),
                ('telephone', models.CharField(default='(085) 975-9830 to 34', max_length=120)),
                ('email', models.EmailField(default='RegionalOffice@caraga.dilg.gov.ph', max_length=254)),
                ('office_hours', models.CharField(blank=True, default='Monday to Friday, 8:00 AM - 5:00 PM', help_text='Left empty, the office hours are not shown at all.', max_length=150)),
                ('facebook_url', models.URLField(blank=True, help_text='Optional. Linked from the contact page and the footer.', verbose_name='Facebook page')),
                ('privacy_notice', models.TextField(default="Personal information collected through this website and through LGMED-iMMS is processed in accordance with the Data Privacy Act of 2012 (Republic Act No. 10173) and is used solely for the Division's monitoring, evaluation and service delivery functions. Enquiries regarding personal data may be directed to the office contacts above.")),
                ('accessibility_statement', models.TextField(default='This website is built to meet recognised accessibility practice: it can be operated by keyboard alone, uses text alternatives for non-text content, maintains sufficient colour contrast, and never relies on colour alone to convey status. If you encounter a barrier to using this site, please tell us using the contact details above so it can be corrected.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'public website content',
                'verbose_name_plural': 'public website content',
            },
        ),
    ]
