# Generated by Django 6.1.1 on 2026-09-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_publicsitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicsitecontent',
            name='office_hours',
            field=models.CharField(blank=True, default='Monday to Thursday, 6:00 AM - 6:00 PM', help_text='Left empty, the office hours are not shown at all.', max_length=150),
        ),
    ]
