# Generated by Django 6.1.1 on 2026-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_publicsitecontent_office_hours_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='notice_posted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the current notice was last changed; each change is shown afresh.', null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='notice_takeover',
            field=models.BooleanField(default=False, help_text='For an announcement no one may miss: the notice covers the whole screen of every signed-in user, with a beep, until they acknowledge it. Pages already open receive it at once.', verbose_name='Cover the page and sound an alert'),
        ),
    ]
