# Generated by Django 6.1.1 on 2026-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_system_notice_takeover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicsitecontent',
            name='privacy_notice',
            field=models.TextField(default="Personal information collected through this website and through LGMED-IMMS is processed in accordance with the Data Privacy Act of 2012 (Republic Act No. 10173) and is used solely for the Division's monitoring, evaluation and service delivery functions. Enquiries regarding personal data may be directed to the office contacts above."),
        ),
    ]
