# Generated by Django 6.1.1 on 2026-09-07 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('MONITORING', 'Monitoring / validation'), ('MEETING', 'Meeting'), ('TRAINING', 'Training / orientation'), ('DEADLINE', 'Submission deadline'), ('OTHER', 'Other')], db_index=True, default='MEETING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for a single-day activity.', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('participants', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False, verbose_name='Show on the public calendar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('lgu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='lgus.lgu', verbose_name='LGU concerned')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': 'calendar activities',
                'ordering': ('start_date', 'start_time', 'title'),
            },
        ),
    ]
