# Generated by Django 6.1.1 on 2026-09-08 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_section_user_section'),
        ('activities', '0001_initial'),
        ('lgus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaractivity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The employee responsible for carrying the activity out, when that is not the owner. Leave empty if the owner does it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Leave empty if the activity has no fixed finish.', null=True),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='owner',
            field=models.ForeignKey(help_text='The employee whose activity this is.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='activity owner'),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='remarks',
            field=models.TextField(blank=True, help_text='Outcome, follow-through, or why the plan changed.'),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='section',
            field=models.ForeignKey(blank=True, help_text="Defaults to the owner's section.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='accounts.section', verbose_name='department / division / section'),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private - only me and my supervisors'), ('ASSIGNED', 'Assigned users - me, the assignee and supervisors'), ('TEAM', 'My department / division / section'), ('ORGANIZATION', 'Everyone in the office')], db_index=True, default='PRIVATE', help_text='Supervisors always see the activity for monitoring. This setting decides which colleagues do.', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendaractivity',
            name='activity_type',
            field=models.CharField(choices=[('MONITORING', 'Monitoring / validation'), ('MEETING', 'Meeting'), ('TRAINING', 'Training / orientation'), ('DEADLINE', 'Submission deadline'), ('FIELDWORK', 'Field work / travel'), ('OFFICE_WORK', 'Office work'), ('LEAVE', 'Leave / unavailable'), ('OTHER', 'Other')], db_index=True, default='MEETING', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendaractivity',
            name='is_published',
            field=models.BooleanField(default=False, help_text="Publishes the activity to the Division's public website. Only office-wide activities may be published.", verbose_name='Show on the public calendar'),
        ),
        migrations.AddIndex(
            model_name='calendaractivity',
            index=models.Index(fields=['owner', 'start_date'], name='activities__owner_i_cc89dd_idx'),
        ),
        migrations.AddIndex(
            model_name='calendaractivity',
            index=models.Index(fields=['assigned_to', 'start_date'], name='activities__assigne_37328c_idx'),
        ),
        migrations.AddIndex(
            model_name='calendaractivity',
            index=models.Index(fields=['visibility', 'start_date'], name='activities__visibil_bf9994_idx'),
        ),
    ]
