# Generated by Django 6.1.1 on 2026-09-28 03:41

import datasync.models
import django.db.models.deletion
import programs.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('file', models.FileField(storage=programs.storage.protected_storage, upload_to=datasync.models.batch_path)),
                ('original_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PREVIEW', 'Awaiting confirmation'), ('COMMITTED', 'Committed'), ('DISCARDED', 'Discarded')], db_index=True, default='PREVIEW', max_length=10)),
                ('sheets', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'spreadsheet sync',
                'verbose_name_plural': 'spreadsheet syncs',
                'ordering': ('-uploaded_at', '-id'),
            },
        ),
    ]
