# Generated by Django 6.1.1 on 2026-09-29 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncbatch',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SyncRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=100)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Valid, with a warning'), ('IMPORTED', 'Imported'), ('DUPLICATE', 'Duplicate'), ('ERROR', 'Error'), ('IGNORED', 'Not a record')], max_length=10)),
                ('key', models.CharField(blank=True, max_length=255)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('record_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='datasync.syncbatch')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['batch', 'status'], name='datasync_sy_batch_i_a14633_idx')],
            },
        ),
    ]
