# Generated by Django 6.1.1 on 2026-09-08 02:27

import django.db.models.deletion
import django.utils.timezone
import incoming.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docket_number', models.CharField(db_index=True, help_text="The office's own reference for this document, e.g. 2026-0417.", max_length=60, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('date_received', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('source_office', models.CharField(help_text='The office, agency or LGU the document came from.', max_length=200, verbose_name='source / office')),
                ('attachment', models.FileField(blank=True, upload_to=incoming.models.incoming_path, verbose_name='document / file attachment')),
                ('initial_remarks', models.TextField(blank=True, help_text='What the receiving officer noted on arrival.')),
                ('status', models.CharField(choices=[('FOR_REVIEW', 'For Division Chief review'), ('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In progress'), ('FOR_ACTION', 'For action'), ('PENDING', 'Pending'), ('RETURNED', 'Returned / for revision'), ('COMPLETED', 'Completed')], db_index=True, default='FOR_REVIEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('due_date', models.DateField(blank=True, help_text='The date by which the action should be completed.', null=True, verbose_name='action due date')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, verbose_name="Division Chief's notes / instructions")),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_remarks', models.TextField(blank=True, verbose_name='assignment remarks / instructions')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_assigned', to=settings.AUTH_USER_MODEL, verbose_name='focal person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_documents', to='documents.documenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'incoming document',
                'ordering': ('-date_received', '-id'),
            },
        ),
        migrations.CreateModel(
            name='IncomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('event_type', models.CharField(choices=[('RECORDED', 'Received and recorded'), ('EDITED', 'Record amended'), ('REVIEWED', 'Reviewed by the Division Chief'), ('ASSIGNED', 'Assigned to a focal person'), ('REASSIGNED', 'Reassigned'), ('ACKNOWLEDGED', 'Acknowledged by the focal person'), ('UPDATED', 'Update provided'), ('RETURNED', 'Returned for revision'), ('COMPLETED', 'Completed')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='incoming.incomingdocument')),
            ],
            options={
                'verbose_name': 'incoming document event',
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IncomingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_taken', models.TextField(verbose_name='action taken')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('FOR_REVIEW', 'For Division Chief review'), ('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In progress'), ('FOR_ACTION', 'For action'), ('PENDING', 'Pending'), ('RETURNED', 'Returned / for revision'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20, verbose_name='status after this action')),
                ('attachment', models.FileField(blank=True, upload_to=incoming.models.update_path, verbose_name='supporting attachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incoming.incomingdocument')),
            ],
            options={
                'verbose_name': 'incoming document update',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='incomingdocument',
            index=models.Index(fields=['status', '-date_received'], name='incoming_in_status_394ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingdocument',
            index=models.Index(fields=['assigned_to', 'status'], name='incoming_in_assigne_04c9c1_idx'),
        ),
    ]
