# Generated by Django 6.1.1 on 2026-09-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingdocument',
            name='status',
            field=models.CharField(choices=[('FOR_REVIEW', 'For Division Chief review'), ('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In progress'), ('FOR_ACTION', 'For action'), ('PENDING', 'Pending'), ('RETURNED', 'Returned / for revision'), ('COMPLETED', 'Completed'), ('IMPORTED', 'Imported from spreadsheet')], db_index=True, default='FOR_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='incomingdocument',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='incomingupdate',
            name='status',
            field=models.CharField(choices=[('FOR_REVIEW', 'For Division Chief review'), ('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In progress'), ('FOR_ACTION', 'For action'), ('PENDING', 'Pending'), ('RETURNED', 'Returned / for revision'), ('COMPLETED', 'Completed'), ('IMPORTED', 'Imported from spreadsheet')], default='IN_PROGRESS', max_length=20, verbose_name='status after this action'),
        ),
    ]
