# Generated by Django 6.1.1 on 2026-09-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0002_alter_incomingdocument_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingdocument',
            name='docket_number',
            field=models.CharField(db_index=True, help_text="The office's own reference for this document, e.g. 2026-0417.", max_length=60, unique=True, verbose_name='DNS number'),
        ),
    ]
