# Generated by Django 6.1.1 on 2026-09-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_alter_incomingdocument_docket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingdocument',
            name='lgmed_code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='LGMED code'),
        ),
        migrations.AlterField(
            model_name='incomingevent',
            name='event_type',
            field=models.CharField(choices=[('RECORDED', 'Received and recorded'), ('EDITED', 'Record amended'), ('REVIEWED', 'Reviewed by the Division Chief'), ('ASSIGNED', 'Assigned to a focal person'), ('REASSIGNED', 'Reassigned'), ('ACKNOWLEDGED', 'Acknowledged by the focal person'), ('UPDATED', 'Update provided'), ('RETURNED', 'Returned for revision'), ('COMPLETED', 'Completed'), ('OUTGOING', 'Outgoing communication recorded')], max_length=20),
        ),
    ]
