# Generated by Django 6.1.1 on 2026-09-07 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontlineService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='service name')),
                ('service_type', models.CharField(choices=[('SIMPLE', 'Simple transaction'), ('COMPLEX', 'Complex transaction'), ('TECHNICAL', 'Highly technical')], db_index=True, default='SIMPLE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('clients', models.CharField(blank=True, help_text='Who may avail of this service, e.g. LGUs, national agencies, public.', max_length=255)),
                ('requirements', models.TextField(blank=True, help_text='One requirement per line.')),
                ('processing_time', models.CharField(blank=True, help_text='For example: 3 working days.', max_length=120)),
                ('fees', models.CharField(blank=True, default='None', help_text="State 'None' where no fee is charged.", max_length=120)),
                ('responsible_office', models.CharField(blank=True, default='Local Government Monitoring and Evaluation Division', max_length=150)),
                ('responsible_person', models.CharField(blank=True, max_length=150)),
                ('is_published', models.BooleanField(default=False, verbose_name='Published on the public website')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
