# Generated by Django 6.1.1 on 2026-09-08 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviation used where space is tight, e.g. LGCDD.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'department / division / section',
                'verbose_name_plural': 'departments / divisions / sections',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The unit this employee belongs to. Determines which team activities they see and how the Chief groups their workload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.section', verbose_name='department / division / section'),
        ),
    ]
