# Generated by Django 6.1.1 on 2026-09-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mfadevice_recoverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_initials',
            field=models.CharField(blank=True, help_text='The initials written into an LGMED code when a document is assigned to this person, e.g. RGFJ. Leave empty to use the first letter of each part of the first and last name.', max_length=10, verbose_name='initials for LGMED codes'),
        ),
    ]
