# Generated by Django 6.1.1 on 2026-09-29 08:12

import programs.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_code_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, storage=programs.storage.protected_storage, upload_to='profile_photos/', verbose_name='profile photo'),
        ),
    ]
