# Generated by Django 6.1.1 on 2026-10-02 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=40)),
                ('allowed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'System Administrator'), ('ADMIN', 'Administrator'), ('LGMED_STAFF', 'LGMED Staff'), ('ENCODER', 'Encoder'), ('VIEWER', 'Viewer')], max_length=20)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'module access by role',
                'verbose_name_plural': 'module access by role',
                'ordering': ('module', 'role'),
                'constraints': [models.UniqueConstraint(fields=('module', 'role'), name='role_module_access_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=40)),
                ('allowed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'module access by account',
                'verbose_name_plural': 'module access by account',
                'ordering': ('module', 'user'),
                'constraints': [models.UniqueConstraint(fields=('module', 'user'), name='user_module_access_unique')],
            },
        ),
    ]
