# Generated by Django 6.1.1 on 2026-09-29 09:51

import django.db.models.deletion
import programs.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'e-SIRA reference sequence',
            },
        ),
        migrations.CreateModel(
            name='EsiraDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(editable=False, max_length=30, unique=True, verbose_name='reference no.')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='What the document is and what it is being signed for.')),
                ('document_type', models.CharField(blank=True, help_text='e.g. Memorandum, Letter, Certification, Report.', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_SIGNATURE', 'Awaiting Signature'), ('OUT_FOR_SIGNATURE', 'Out for Signature'), ('PARTIALLY_SIGNED', 'Partially Signed'), ('FULLY_SIGNED', 'Fully Signed'), ('ROUTED', 'Routed'), ('ROUTING_COMPLETED', 'Routing Completed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('source', models.CharField(choices=[('UPLOAD', 'Uploaded PDF'), ('SCAN', 'Scanned images')], default='UPLOAD', max_length=10)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True, help_text='Why the document was rejected or cancelled.')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The employee who uploaded the document and controls its route.', on_delete=django.db.models.deletion.PROTECT, related_name='esira_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-SIRA document',
                'verbose_name_plural': 'e-SIRA documents',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('ORIGINAL', 'Original upload'), ('SIGNED', 'Signed')], max_length=10)),
                ('file', models.FileField(max_length=255, storage=programs.storage.protected_storage, upload_to='esira/%Y/%m/')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='esira.esiradocument')),
            ],
            options={
                'verbose_name': 'e-SIRA document version',
                'ordering': ('document', 'number'),
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document_reference', models.CharField(blank=True, max_length=30)),
                ('actor_label', models.CharField(max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(choices=[('UPLOADED', 'Document uploaded'), ('VIEWED', 'Document viewed'), ('DOWNLOADED', 'Document downloaded'), ('BOX_ADDED', 'Signature box added'), ('BOX_MODIFIED', 'Signature box modified'), ('BOX_REMOVED', 'Signature box removed'), ('SIGNED', 'Document signed'), ('SIGN_FAILED', 'Signing refused'), ('ROUTED', 'Document routed'), ('RECEIVED', 'Document received'), ('APPROVED', 'Document approved'), ('REVIEWED', 'Document reviewed'), ('ACKNOWLEDGED', 'Document acknowledged'), ('FORWARDED', 'Document forwarded'), ('REJECTED', 'Document rejected'), ('COMPLETED', 'Document completed'), ('CANCELLED', 'Document cancelled'), ('SIGNATURES_VERIFIED', 'Signatures verified'), ('INTEGRITY_FAILURE', 'File integrity check failed'), ('CERT_REGISTERED', 'Certificate registered'), ('CERT_VERIFIED', 'Certificate verified'), ('CERT_REJECTED', 'Certificate rejected'), ('CERT_REVOKED', 'Certificate revoked')], db_index=True, max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='esira.esiradocument')),
            ],
            options={
                'verbose_name': 'e-SIRA audit entry',
                'verbose_name_plural': 'e-SIRA audit entries',
                'ordering': ('-timestamp', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('SIGN', 'Signature'), ('APPROVE', 'Approval'), ('REVIEW', 'Review / initials'), ('ACKNOWLEDGE', 'For information / acknowledgement')], max_length=12)),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='purpose / action required')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PENDING', 'Awaiting action'), ('RECEIVED', 'Received'), ('SIGNED', 'Signed'), ('APPROVED', 'Approved'), ('REVIEWED', 'Reviewed'), ('ACKNOWLEDGED', 'Acknowledged'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='esira.esiradocument')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esira_steps', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'routing step',
                'ordering': ('document', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(max_length=20)),
                ('certificate_subject', models.CharField(max_length=500)),
                ('certificate_issuer', models.CharField(max_length=500)),
                ('certificate_serial', models.CharField(max_length=80)),
                ('certificate_fingerprint', models.CharField(max_length=64)),
                ('certificate_not_after', models.DateTimeField()),
                ('chain_trusted', models.BooleanField(help_text='Whether the certificate chained to a configured PNPKI root.')),
                ('trust_note', models.CharField(blank=True, max_length=500)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('field_names', models.JSONField(default=list)),
                ('timestamped', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esira_signatures', to=settings.AUTH_USER_MODEL)),
                ('result_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='esira.documentversion')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='esira.documentversion')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='esira.esiradocument')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='esira.routingstep')),
            ],
            options={
                'verbose_name': 'digital signature',
                'ordering': ('signed_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SignatureBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(help_text='1-based page number.')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('field_name', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='esira.esiradocument')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='esira.digitalsignature')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esira_signature_boxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signature box',
                'verbose_name_plural': 'signature boxes',
                'ordering': ('page', 'y', 'x', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SigningCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_pem', models.TextField(help_text='The public certificate, PEM encoded.')),
                ('subject', models.CharField(max_length=500)),
                ('subject_common_name', models.CharField(blank=True, max_length=255)),
                ('subject_email', models.CharField(blank=True, max_length=255)),
                ('issuer', models.CharField(max_length=500)),
                ('serial_number', models.CharField(max_length=80)),
                ('fingerprint_sha256', models.CharField(max_length=64, unique=True, verbose_name='SHA-256 fingerprint')),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('chain_trusted', models.BooleanField(default=False)),
                ('chain_note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.CharField(blank=True, max_length=500)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esira_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signing certificate',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='esira.signingcertificate'),
        ),
        migrations.AddIndex(
            model_name='esiradocument',
            index=models.Index(fields=['owner', 'status'], name='esira_esira_owner_i_06f692_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='esira_version_unique_number'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['document', '-timestamp'], name='esira_audit_documen_80ee8a_idx'),
        ),
        migrations.AddIndex(
            model_name='routingstep',
            index=models.Index(fields=['recipient', 'status'], name='esira_routi_recipie_ec8eac_idx'),
        ),
    ]
