# Generated by Django 6.1.1 on 2026-10-08 06:41

import django.db.models.deletion
import programs.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esira', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signingcertificate',
            name='passphrase_sealed',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signingcertificate',
            name='pkcs12_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='signingcertificate',
            name='pkcs12_sealed',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signingcertificate',
            name='stored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('UPLOADED', 'Document uploaded'), ('VIEWED', 'Document viewed'), ('DOWNLOADED', 'Document downloaded'), ('BOX_ADDED', 'Signature box added'), ('BOX_MODIFIED', 'Signature box modified'), ('BOX_REMOVED', 'Signature box removed'), ('SIGNED', 'Document signed'), ('SIGN_FAILED', 'Signing refused'), ('ROUTED', 'Document routed'), ('RECEIVED', 'Document received'), ('APPROVED', 'Document approved'), ('REVIEWED', 'Document reviewed'), ('ACKNOWLEDGED', 'Document acknowledged'), ('FORWARDED', 'Document forwarded'), ('REJECTED', 'Document rejected'), ('COMPLETED', 'Document completed'), ('CANCELLED', 'Document cancelled'), ('SIGNATURES_VERIFIED', 'Signatures verified'), ('INTEGRITY_FAILURE', 'File integrity check failed'), ('CERT_REGISTERED', 'Certificate registered'), ('CERT_VERIFIED', 'Certificate verified'), ('CERT_REJECTED', 'Certificate rejected'), ('CERT_REVOKED', 'Certificate revoked'), ('CERT_STORED', 'Certificate file stored'), ('CERT_REMOVED', 'Stored certificate file removed'), ('CERT_PASSWORD_VIEWED', 'Certificate password viewed'), ('SIGNING_SETTINGS', 'Signing settings changed')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SignerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_passphrase', models.BooleanField(default=True, help_text='Ask for the certificate password on every signing action.', verbose_name='require .p12 password when signing')),
                ('signature_image', models.ImageField(blank=True, storage=programs.storage.protected_storage, upload_to='esira/signatures/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esira_signer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signer profile',
            },
        ),
    ]
