# Generated by Django 6.1.1 on 2026-10-08 06:57

import django.db.models.deletion
import programs.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esira', '0002_signer_profile_stored_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signerprofile',
            name='preferred_style',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='SignatureStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(storage=programs.storage.protected_storage, upload_to='esira/styles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esira_signature_styles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signature style',
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
