# Generated by Django 6.1.1 on 2026-09-07 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('capital', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='LGU name')),
                ('lgu_type', models.CharField(choices=[('PROVINCE', 'Province'), ('CITY', 'City'), ('MUNICIPALITY', 'Municipality')], db_index=True, max_length=20, verbose_name='LGU type')),
                ('is_independent', models.BooleanField(default=False, help_text='Tick for highly urbanised or independent component cities.', verbose_name='Independent of the province')),
                ('income_class', models.CharField(blank=True, choices=[('1', '1st class'), ('2', '2nd class'), ('3', '3rd class'), ('4', '4th class'), ('5', '5th class'), ('6', '6th class')], max_length=2)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, help_text='Local Chief Executive or designated focal person.', max_length=150)),
                ('contact_position', models.CharField(blank=True, max_length=120)),
                ('contact_number', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('PARTIAL', 'Partially compliant'), ('NON_COMPLIANT', 'Non-compliant'), ('NOT_ASSESSED', 'Not yet assessed')], db_index=True, default='NOT_ASSESSED', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active in the directory')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgus', to='lgus.province')),
            ],
            options={
                'verbose_name': 'LGU',
                'verbose_name_plural': 'LGUs',
                'ordering': ('province__name', 'lgu_type', 'name'),
                'indexes': [models.Index(fields=['lgu_type', 'compliance_status'], name='lgus_lgu_lgu_typ_9fb70b_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'province'), name='unique_lgu_name_per_province')],
            },
        ),
    ]
