# Generated by Django 6.1.1 on 2026-09-28 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_code', models.CharField(help_text="The office's control code, e.g. LGMED-13 - (DBA) - 2026-01-05-0001.", max_length=255, unique=True)),
                ('date_sent', models.DateField(blank=True, db_index=True, help_text='Read from the control code.', null=True)),
                ('communication_type', models.CharField(blank=True, max_length=120, verbose_name='type of communication')),
                ('subject', models.TextField(blank=True, verbose_name='subject / title')),
                ('sent_to', models.TextField(blank=True)),
                ('sent_via', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('incoming_reference', models.CharField(blank=True, help_text='The incoming document this replies to, where there is one.', max_length=120, verbose_name='DMS number (incoming)')),
                ('dms_number', models.CharField(blank=True, max_length=120, verbose_name='DMS number (outgoing)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'outgoing document',
                'ordering': ('-date_sent', '-id'),
            },
        ),
    ]
