# Generated by Django 6.1.1 on 2026-09-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCodeCounter',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'LGMED code counter',
            },
        ),
    ]
