# Generated by Django 6.1.1 on 2026-09-29 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0004_lgmed_code'),
        ('outgoing', '0002_controlcodecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingdocument',
            name='incoming',
            field=models.OneToOneField(blank=True, help_text='The incoming document this action answers, where there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_record', to='incoming.incomingdocument', verbose_name='incoming document'),
        ),
        migrations.AlterField(
            model_name='outgoingdocument',
            name='control_code',
            field=models.CharField(help_text='The LGMED code, e.g. LGMED-13 - DBA - 2026-01-05-0001.', max_length=255, unique=True),
        ),
    ]
