# Generated by Django 6.1.1 on 2026-09-29 03:22

import outgoing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing', '0004_lgmed_code_without_parentheses'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingdocument',
            name='file',
            field=models.FileField(blank=True, help_text='The communication as sent, e.g. the signed and scanned reply.', upload_to=outgoing.models.outgoing_path, verbose_name='file of the communication'),
        ),
    ]
