# Generated by Django 6.1.1 on 2026-09-07 05:45

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='report title')),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMESTRAL', 'Semestral'), ('ANNUAL', 'Annual'), ('SPECIAL', 'Special report')], db_index=True, default='QUARTERLY', max_length=20, verbose_name='reporting period')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('summary', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(blank=True, upload_to=reports.models.report_path)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FOR_REVIEW', 'For review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('RETURNED', 'Returned')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_on', models.DateField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, help_text='Notes from the reviewing officer.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='programs.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-year', '-submitted_on', '-created_at'),
                'indexes': [models.Index(fields=['status', 'year'], name='reports_rep_status_d4e963_idx')],
            },
        ),
    ]
