# Generated by Django 6.1.1 on 2026-09-07 05:45

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='document title')),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('office', models.CharField(default='Local Government Monitoring and Evaluation Division', max_length=150, verbose_name='office / division')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=documents.models.document_path)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Only published documents are shown publicly.', verbose_name='Available on the public website')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
            ],
            options={
                'ordering': ('-year', '-created_at'),
                'indexes': [models.Index(fields=['year', 'status'], name='documents_d_year_789f6f_idx')],
            },
        ),
    ]
