# Generated by Django 6.1.1 on 2026-09-09 10:11

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_section_user_section'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='e.g. NAP-RDS-2026-014, or the board resolution number.', max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('approved_on', models.DateField()),
                ('approved_by', models.CharField(help_text='The officer or body that granted the authority.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'disposal authority',
                'verbose_name_plural': 'disposal authorities',
                'ordering': ('-approved_on', 'reference'),
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('event_type', models.CharField(choices=[('REGISTERED', 'Registered'), ('UPLOADED', 'File uploaded'), ('VIEWED', 'Viewed'), ('DOWNLOADED', 'Downloaded'), ('EDITED', 'Details edited'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('STATUS_CHANGED', 'Status changed'), ('VERSION_UPLOADED', 'New version uploaded'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('RETENTION_SET', 'Retention set'), ('ARCHIVED', 'Archived'), ('RESTORED', 'Restored from archive'), ('DISPOSED', 'Disposed')], db_index=True, max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'document event',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=documents.models.version_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.TextField(blank=True, help_text='Why this version replaced the one before it.', verbose_name='reason for revision')),
            ],
            options={
                'verbose_name': 'document version',
                'ordering': ('-version_number',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_assigned', to=settings.AUTH_USER_MODEL, verbose_name='assigned personnel / focal person'),
        ),
        migrations.AddField(
            model_name='document',
            name='assignment_remarks',
            field=models.TextField(blank=True, verbose_name='assignment remarks / instructions'),
        ),
        migrations.AddField(
            model_name='document',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='date_created',
            field=models.DateField(blank=True, db_index=True, help_text='The date written on the document itself.', null=True, verbose_name='date of document'),
        ),
        migrations.AddField(
            model_name='document',
            name='date_received',
            field=models.DateField(blank=True, db_index=True, help_text='When the document arrived at the Division. Leave blank for a document the Division itself created.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='disposal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='disposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='disposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='due_date',
            field=models.DateField(blank=True, help_text='The date by which the action should be completed.', null=True, verbose_name='action due date'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(help_text='The person answerable for this document. Defaults to whoever registers it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_owned', to=settings.AUTH_USER_MODEL, verbose_name='owner / responsible personnel'),
        ),
        migrations.AddField(
            model_name='document',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_disposition',
            field=models.CharField(choices=[('ACTIVE', 'Within retention period'), ('FOR_REVIEW', 'For retention review'), ('FOR_DISPOSAL', 'For disposal'), ('PERMANENT', 'Permanent preservation'), ('DISPOSED', 'Disposed')], db_index=True, default='ACTIVE', max_length=20, verbose_name='retention decision'),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_until',
            field=models.DateField(blank=True, db_index=True, help_text="Worked out from the document type's retention period when the document is completed. May be overridden.", null=True, verbose_name='retention period ends'),
        ),
        migrations.AddField(
            model_name='document',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='sender',
            field=models.CharField(blank=True, help_text='The office, agency, LGU or person the document came from.', max_length=200, verbose_name='sender / source'),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, help_text='What the document is about, in one line.', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='The unit responsible for this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.section', verbose_name='division / unit'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='code',
            field=models.CharField(blank=True, help_text='Short code used in control numbers, e.g. MEMO.', max_length=12),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='retention_action',
            field=models.CharField(choices=[('REVIEW', 'Review before disposal'), ('DISPOSE', 'Dispose'), ('PERMANENT', 'Preserve permanently')], default='REVIEW', help_text='What the records officer should do when the period runs out.', max_length=10, verbose_name='action at end of retention'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='retention_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How long a completed document of this type is kept before it falls due for retention review. Leave blank if no period has been set for this type.', null=True, verbose_name='retention period (years)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='PDF, Word, Excel, PowerPoint or an image. The current version - every earlier one is kept.', upload_to=documents.models.document_path, verbose_name='document file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Only a completed document may be offered publicly.', verbose_name='Available on the public website'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, help_text="The office's control number for this document. Left blank, the system issues the next one for the year.", max_length=60, unique=True, verbose_name='document / reference / control number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received'), ('FOR_REVIEW', 'For review'), ('FOR_ASSIGNMENT', 'For assignment'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('FOR_APPROVAL', 'For approval'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='disposal_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='documents.disposalauthority'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', '-created_at'], name='documents_d_status_dead80_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='documents_d_owner_i_683479_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['assigned_to', 'status'], name='documents_d_assigne_d59c52_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['retention_disposition', 'retention_until'], name='documents_d_retenti_f50d83_idx'),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['document', '-occurred_at'], name='documents_d_documen_ff6e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='documents_d_event_t_0b0b9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_version_per_document'),
        ),
    ]
