# Generated by Django 6.1.1 on 2026-09-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_owner_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNumberSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'control number sequence',
                'ordering': ('-year',),
            },
        ),
    ]
