# Generated by Django 6.1.1 on 2026-09-29 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_control_number_sequence'),
        ('incoming', '0004_lgmed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='incoming',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_entry', to='incoming.incomingdocument', verbose_name='incoming document'),
        ),
    ]
