# Generated by Django 6.1.1 on 2026-09-29 03:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_incoming_link'),
        ('incoming', '0004_lgmed_code'),
        ('outgoing', '0005_capture_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='outgoing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_entry', to='outgoing.outgoingdocument', verbose_name='outgoing communication'),
        ),
        migrations.CreateModel(
            name='SupportingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('UPDATE', "Focal person's update"), ('OUTGOING', 'Outgoing communication')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, max_length=255, upload_to='')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_files', to='documents.document')),
                ('incoming_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incoming.incomingupdate')),
                ('outgoing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='outgoing.outgoingdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supporting file',
                'ordering': ('-uploaded_at', '-id'),
            },
        ),
    ]
