# Generated by Django 6.1.1 on 2026-09-07 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(help_text="The actor's name as it was at the time of the action.", max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Signed in'), ('LOGOUT', 'Signed out'), ('LOGIN_FAILED', 'Failed sign-in'), ('PASSWORD_RESET', 'Password reset'), ('ROLE_CHANGE', 'Role changed'), ('ACTIVATION', 'Account activated'), ('DEACTIVATION', 'Account deactivated'), ('EXPORT', 'Exported records'), ('ACCESS_DENIED', 'Access denied')], db_index=True, max_length=20)),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Field-level before and after values for an update.')),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'ordering': ('-timestamp', '-id'),
                'indexes': [models.Index(fields=['action', '-timestamp'], name='audit_audit_action_c194db_idx'), models.Index(fields=['target_model', '-timestamp'], name='audit_audit_target__d73104_idx')],
            },
        ),
    ]
