# Generated by Django 6.1.1 on 2026-09-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Signed in'), ('LOGOUT', 'Signed out'), ('LOGIN_FAILED', 'Failed sign-in'), ('PASSWORD_RESET', 'Password reset'), ('ROLE_CHANGE', 'Role changed'), ('ACTIVATION', 'Account activated'), ('DEACTIVATION', 'Account deactivated'), ('EXPORT', 'Exported records'), ('ACCESS_DENIED', 'Access denied'), ('UPLOAD', 'Uploaded a file'), ('SCREEN', 'Screened a file'), ('SUBMIT', 'Submitted for review'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('REQUEST_REVISION', 'Requested revision'), ('PUBLISH', 'Published'), ('UNPUBLISH', 'Unpublished'), ('ARCHIVE', 'Archived'), ('RESTORE', 'Restored from the archive')], db_index=True, max_length=20),
        ),
    ]
