# Generated by Django 6.1.1 on 2026-09-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Signed in'), ('LOGOUT', 'Signed out'), ('LOGIN_FAILED', 'Failed sign-in'), ('PASSWORD_RESET', 'Password reset'), ('ROLE_CHANGE', 'Role changed'), ('ACTIVATION', 'Account activated'), ('DEACTIVATION', 'Account deactivated'), ('EXPORT', 'Exported records'), ('ACCESS_DENIED', 'Access denied'), ('UPLOAD', 'Uploaded a file'), ('SCREEN', 'Screened a file'), ('SUBMIT', 'Submitted for review'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('REQUEST_REVISION', 'Requested revision'), ('PUBLISH', 'Published'), ('UNPUBLISH', 'Unpublished'), ('ARCHIVE', 'Archived'), ('RESTORE', 'Restored from the archive'), ('MFA_ENABLED', 'Two-step verification on'), ('MFA_DISABLED', 'Two-step verification off'), ('MFA_CODES_RENEWED', 'Renewed recovery codes'), ('MFA_RECOVERY_USED', 'Used a recovery code'), ('PRIVACY_ACKNOWLEDGED', 'Acknowledged the privacy notice'), ('SYNC', 'Synchronised from a spreadsheet'), ('SIGN', 'Digitally signed'), ('ROUTE', 'Routed for signature/approval'), ('COMPLETE', 'Completed'), ('CANCEL', 'Cancelled')], db_index=True, max_length=20),
        ),
    ]
