# Generated by Django 6.1.1 on 2026-09-07 07:49

import announcements.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='headline')),
                ('slug', models.SlugField(blank=True, help_text='Left blank, this is generated from the headline.', max_length=280, unique=True)),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('ADVISORY', 'Advisory'), ('ISSUANCE', 'Issuance'), ('ACTIVITY', 'Activity'), ('COMMENDATION', 'Commendation')], db_index=True, default='NEWS', max_length=20)),
                ('published_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='The date shown on the item. A future date holds it back.', verbose_name='date published')),
                ('summary', models.TextField(help_text='Two or three sentences. This is what appears in the news list.', verbose_name='lead paragraph')),
                ('body', models.TextField(blank=True, help_text="Optional. One paragraph per line; shown on the item's own page.", verbose_name='full text')),
                ('image', models.FileField(blank=True, help_text="JPG, PNG or WebP. Shown as the item's thumbnail.", upload_to=announcements.models.announcement_image_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif'))], verbose_name='photograph')),
                ('image_alt', models.CharField(blank=True, help_text='Describes the photograph for readers using a screen reader.', max_length=255, verbose_name='photograph description')),
                ('location', models.CharField(blank=True, help_text='Where it happened, for example: Butuan City.', max_length=150)),
                ('source_url', models.URLField(blank=True, help_text='Optional link to the full post or issuance elsewhere.', verbose_name='read more at')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published on the public website')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items lead the homepage news section.', verbose_name='Feature on the homepage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-published_on', '-created_at'),
                'indexes': [models.Index(fields=['is_published', '-published_on'], name='announcemen_is_publ_831809_idx')],
            },
        ),
    ]
