# Generated by Django 6.1.1 on 2026-09-07 05:45

import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgus', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='For example: SGLG Assessment - Table Validation.', max_length=255, verbose_name='activity')),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('monitoring_date', models.DateField(db_index=True)),
                ('monitoring_team', models.CharField(help_text='Names of the personnel who conducted the activity.', max_length=255)),
                ('findings', models.TextField(blank=True, help_text='Observations made during the activity.')),
                ('recommendations', models.TextField(blank=True)),
                ('follow_up_action', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='follow-up due date')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('FOR_REVIEW', 'For review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('lgu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_activities', to='lgus.lgu', verbose_name='LGU')),
                ('program', models.ForeignKey(blank=True, help_text='The program this activity was conducted under, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_activities', to='programs.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': 'monitoring activities',
                'ordering': ('-monitoring_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MonitoringAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=monitoring.models.attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='monitoring.monitoringactivity')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='monitoringactivity',
            index=models.Index(fields=['status', 'monitoring_date'], name='monitoring__status_bf3fa4_idx'),
        ),
    ]
