# Generated by Django 6.1.1 on 2026-09-07 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'program categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='program title')),
                ('reference_number', models.CharField(blank=True, help_text='Issuance or reference number, if any.', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True, help_text='What the program is intended to achieve.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20)),
                ('lead_office', models.CharField(blank=True, default='Local Government Monitoring and Evaluation Division', max_length=150)),
                ('focal_person', models.CharField(blank=True, max_length=150)),
                ('covered_lgus', models.ManyToManyField(blank=True, help_text='Leave empty if the program covers the whole region.', related_name='programs', to='lgus.lgu', verbose_name='covered LGUs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.programcategory')),
            ],
            options={
                'ordering': ('-start_date', 'title'),
                'indexes': [models.Index(fields=['status', 'start_date'], name='programs_pr_status_6efba9_idx')],
            },
        ),
    ]
