# Generated by Django 6.1.1 on 2026-09-14 01:10

import django.core.validators
import django.db.models.deletion
import programs.models
import programs.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_section_user_section'),
        ('lgus', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Written for the public. Do not include personal details.')),
                ('focal_person', models.CharField(blank=True, help_text='Internal reference only; never shown on the public website.', max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20, verbose_name='implementation status')),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For review'), ('SCREENING', 'Screening in progress'), ('REVIEW_REQUIRED', 'Review required'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('slug', models.SlugField(blank=True, default='', help_text='Used in the public web address. Never a database number.', max_length=280)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, help_text="The reviewer's remarks. Internal.")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Municipality, city or venue. Never a private address.', max_length=200)),
                ('accomplishment', models.TextField(blank=True, help_text='What was achieved. Written for the public.', verbose_name='accomplishment / remarks')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ('-activity_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Written for the public. Do not include personal details.')),
                ('focal_person', models.CharField(blank=True, help_text='Internal reference only; never shown on the public website.', max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20, verbose_name='implementation status')),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For review'), ('SCREENING', 'Screening in progress'), ('REVIEW_REQUIRED', 'Review required'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('slug', models.SlugField(blank=True, default='', help_text='Used in the public web address. Never a database number.', max_length=280)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, help_text="The reviewer's remarks. Internal.")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Written for the public. Do not include personal details.')),
                ('focal_person', models.CharField(blank=True, help_text='Internal reference only; never shown on the public website.', max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20, verbose_name='implementation status')),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For review'), ('SCREENING', 'Screening in progress'), ('REVIEW_REQUIRED', 'Review required'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('slug', models.SlugField(blank=True, default='', help_text='Used in the public web address. Never a database number.', max_length=280)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, help_text="The reviewer's remarks. Internal.")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sub-project',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What this file is. Shown publicly if the file is released.', max_length=200, verbose_name='document title')),
                ('kind', models.CharField(choices=[('ISSUANCE', 'Issuance or memorandum'), ('REPORT', 'Report or accomplishment record'), ('GUIDELINE', 'Guidelines or primer'), ('PRESENTATION', 'Presentation'), ('PHOTO', 'Photograph'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other supporting file')], default='OTHER', max_length=20, verbose_name='type of document')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('internal_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(help_text='PDF, Word, Excel, PowerPoint, JPG or PNG. Up to 25 MB.', storage=programs.storage.protected_storage, upload_to=programs.models.internal_document_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png'))], verbose_name='file')),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0, editable=False)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=120)),
                ('is_image', models.BooleanField(db_index=True, default=False, editable=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_file', models.FileField(blank=True, editable=False, help_text='Written by the system when the document is published.', upload_to=programs.models.public_document_path, verbose_name='approved public copy')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded - internal'), ('SCREENING', 'Screening'), ('SCREENED', 'Screened - awaiting review'), ('APPROVED', 'Approved for publication'), ('REJECTED', 'Rejected'), ('FOR_REVISION', 'Revision requested'), ('PUBLISHED', 'Published'), ('WITHDRAWN', 'Withdrawn from the public website')], db_index=True, default='UPLOADED', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low risk'), ('REVIEW_REQUIRED', 'Review required'), ('HIGH', 'High risk')], db_index=True, default='REVIEW_REQUIRED', help_text='Set by the automated screening. An unscreened file is treated as needing review, never as safe.', max_length=20, verbose_name='screening result')),
                ('screened_at', models.DateTimeField(blank=True, null=True)),
                ('screening_findings', models.JSONField(blank=True, default=list, help_text='What the screening flagged, with masked evidence.')),
                ('screening_notes', models.TextField(blank=True, help_text='How the file was read, and anything the scanner could not do.')),
                ('text_extracted', models.BooleanField(default=False, help_text="Whether the scanner could read the file's text at all.")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'supporting document',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('outcome_code', 'title')},
        ),
        migrations.RemoveIndex(
            model_name='program',
            name='programs_pr_status_6efba9_idx',
        ),
        migrations.AddField(
            model_name='program',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='outcome_code',
            field=models.CharField(choices=[('OO1', 'Excellence in Local Governance Upheld'), ('OO2', 'Peaceful, Orderly, Safe, and Secure Communities Strengthened'), ('OO3', 'Resilient Communities Reinforced'), ('OO4', 'Inclusive Communities Enabled'), ('OO5', 'Highly Trusted Department and Partner')], db_index=True, default='OO1', max_length=10, verbose_name='organizational outcome'),
        ),
        migrations.AddField(
            model_name='program',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='program',
            name='publication_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For review'), ('SCREENING', 'Screening in progress'), ('REVIEW_REQUIRED', 'Review required'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='responsible_office',
            field=models.ForeignKey(blank=True, help_text='The unit answerable for this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.section', verbose_name='responsible office / division'),
        ),
        migrations.AddField(
            model_name='program',
            name='review_comments',
            field=models.TextField(blank=True, help_text="The reviewer's remarks. Internal."),
        ),
        migrations.AddField(
            model_name='program',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Used in the public web address. Never a database number.', max_length=280),
        ),
        migrations.AddField(
            model_name='program',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='unpublished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='unpublished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.programcategory'),
        ),
        migrations.AlterField(
            model_name='program',
            name='covered_lgus',
            field=models.ManyToManyField(blank=True, help_text='Leave empty if the programme covers the whole region.', related_name='programs', to='lgus.lgu', verbose_name='covered LGUs'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Written for the public. Do not include personal details.'),
        ),
        migrations.AlterField(
            model_name='program',
            name='focal_person',
            field=models.CharField(blank=True, help_text='Internal reference only; never shown on the public website.', max_length=150),
        ),
        migrations.AlterField(
            model_name='program',
            name='objectives',
            field=models.TextField(blank=True, help_text='What the programme is intended to achieve.'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20, verbose_name='implementation status'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['outcome_code', 'publication_status'], name='programs_pr_outcome_bda6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['publication_status', '-updated_at'], name='programs_pr_publica_076df6_idx'),
        ),
        migrations.AddField(
            model_name='activity',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by'),
        ),
        migrations.AddField(
            model_name='activity',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible_office',
            field=models.ForeignKey(blank=True, help_text='The unit answerable for this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.section', verbose_name='responsible office / division'),
        ),
        migrations.AddField(
            model_name='activity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='unpublished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AddField(
            model_name='project',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by'),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='programs.program', verbose_name='parent program'),
        ),
        migrations.AddField(
            model_name='project',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible_office',
            field=models.ForeignKey(blank=True, help_text='The unit answerable for this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.section', verbose_name='responsible office / division'),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='unpublished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='programs.project'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproject',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_projects', to='programs.project', verbose_name='parent project'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproject',
            name='responsible_office',
            field=models.ForeignKey(blank=True, help_text='The unit answerable for this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.section', verbose_name='responsible office / division'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproject',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproject',
            name='unpublished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sub_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='programs.subproject', verbose_name='parent sub-project'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='programs.activity'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='programs.program'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='programs.project'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='sub_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='programs.subproject'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['program', 'publication_status'], name='programs_pr_program_188efe_idx'),
        ),
        migrations.AddIndex(
            model_name='subproject',
            index=models.Index(fields=['project', 'publication_status'], name='programs_su_project_6ee8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['publication_status', '-activity_date'], name='programs_ac_publica_eb0255_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('sub_project__isnull', True)), models.Q(('project__isnull', True), ('sub_project__isnull', False)), _connector='OR'), name='programs_activity_has_exactly_one_parent'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['status', '-uploaded_at'], name='programs_su_status_7b9d63_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['risk_level', 'status'], name='programs_su_risk_le_a8fd5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportingdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('program__isnull', False), ('project__isnull', True), ('sub_project__isnull', True)), models.Q(('activity__isnull', True), ('program__isnull', True), ('project__isnull', False), ('sub_project__isnull', True)), models.Q(('activity__isnull', True), ('program__isnull', True), ('project__isnull', True), ('sub_project__isnull', False)), models.Q(('activity__isnull', False), ('program__isnull', True), ('project__isnull', True), ('sub_project__isnull', True)), _connector='OR'), name='programs_document_has_exactly_one_owner'),
        ),
    ]
