# Generated by Django 6.1.1 on 2026-09-14 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_ppa_public_identifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the public web address. Never a database number.', max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the public web address. Never a database number.', max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the public web address. Never a database number.', max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the public web address. Never a database number.', max_length=280, unique=True),
        ),
    ]
