# Generated by Django 6.1.1 on 2026-09-14 02:04

import django.core.validators
import django.db.models.deletion
import programs.models
import programs.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_activity_public_token_alter_activity_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text='e.g. LGMED Memorandum No. 2026-014, or the issuance number.', max_length=120, unique=True)),
                ('title', models.CharField(help_text='What the memorandum authorises, in its own words.', max_length=255, verbose_name='subject')),
                ('approved_on', models.DateField(verbose_name='date issued')),
                ('approved_by', models.CharField(help_text='The officer or body that issued it, e.g. the Regional Director.', max_length=200)),
                ('scope', models.TextField(blank=True, help_text='What this authority covers, and anything it excludes.')),
                ('memorandum', models.FileField(blank=True, help_text='The signed issuance. Stored internally; never published.', storage=programs.storage.protected_storage, upload_to=programs.models.authority_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png'))], verbose_name='scanned memorandum')),
                ('effective_from', models.DateField(blank=True, help_text='Leave empty if it takes effect on the date it was issued.', null=True)),
                ('effective_until', models.DateField(blank=True, help_text='Leave empty if it does not expire.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Clear this to withdraw the authority. Files already published under it stay published.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'publication authority',
                'verbose_name_plural': 'publication authorities',
                'ordering': ('-approved_on', 'reference'),
            },
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='authority',
            field=models.ForeignKey(blank=True, help_text="The memorandum authorising this file's release. Required before it can go on the public website.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='programs.publicationauthority', verbose_name='published under'),
        ),
        migrations.AddIndex(
            model_name='publicationauthority',
            index=models.Index(fields=['is_active', '-approved_on'], name='programs_pu_is_acti_b46319_idx'),
        ),
    ]
