# Generated by Django 6.1.1 on 2026-09-15 23:56

from django.conf import settings
from django.db import migrations, models


def number_existing_documents(apps, schema_editor):
    """
    Give every file already on the system a position in its record's gallery.

    Without this the whole table sits at zero, and the first photograph
    uploaded after the migration takes position 1 - which would place it
    *behind* pictures that have been on the public website for months. The
    order used here is the order they arrived in, which is what the tie-break
    in `SupportingDocumentQuerySet.photographs()` would have produced anyway.
    """
    SupportingDocument = apps.get_model("programs", "SupportingDocument")
    counters = {}
    updated = []
    for document in SupportingDocument.objects.order_by("uploaded_at", "pk").iterator():
        owner = (
            document.program_id, document.project_id,
            document.sub_project_id, document.activity_id,
        )
        counters[owner] = counters.get(owner, 0) + 1
        document.display_order = counters[owner]
        updated.append(document)
        if len(updated) >= 500:
            SupportingDocument.objects.bulk_update(updated, ["display_order"])
            updated = []
    if updated:
        SupportingDocument.objects.bulk_update(updated, ["display_order"])


def unnumber(apps, schema_editor):
    """Reversing the migration drops the column, so there is nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_publicationauthority_supportingdocument_authority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Where this photograph sits in the public gallery. Set when the file is uploaded and changed on the arrange page.', verbose_name='position in the gallery'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['is_image', 'display_order'], name='programs_su_is_imag_b6eba9_idx'),
        ),
        migrations.RunPython(number_existing_documents, unnumber),
    ]
