# Generated by Django 6.1.1 on 2026-09-16 05:46

"""
Records why a supporting document came off the public website.

Existing withdrawn rows keep the default, False: nothing here knows whether
they came down with their record or on their own, and the safe reading of an
unknown withdrawal is the deliberate one. Those files stay off the website
until somebody publishes them, which is now a single click on the record page
rather than a second trip through the review screen.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_supportingdocument_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='withdrawn_with_record',
            field=models.BooleanField(default=False, help_text='The file came off the website because the record carrying it did, rather than being taken down on its own.'),
        ),
    ]
