# Generated by Django 6.1.1 on 2026-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_supportingdocument_withdrawn_with_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='about_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “About”.', max_length=60, verbose_name='description heading'),
        ),
        migrations.AddField(
            model_name='activity',
            name='accomplishment_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Accomplishment”.', max_length=60, verbose_name='accomplishment heading'),
        ),
        migrations.AddField(
            model_name='activity',
            name='photographs_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Photographs”.', max_length=60, verbose_name='photographs heading'),
        ),
        migrations.AddField(
            model_name='program',
            name='about_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “About”.', max_length=60, verbose_name='description heading'),
        ),
        migrations.AddField(
            model_name='program',
            name='objectives_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Objectives”.', max_length=60, verbose_name='objectives heading'),
        ),
        migrations.AddField(
            model_name='program',
            name='photographs_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Photographs”.', max_length=60, verbose_name='photographs heading'),
        ),
        migrations.AddField(
            model_name='program',
            name='projects_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Projects”.', max_length=60, verbose_name='projects list heading'),
        ),
        migrations.AddField(
            model_name='project',
            name='about_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “About”.', max_length=60, verbose_name='description heading'),
        ),
        migrations.AddField(
            model_name='project',
            name='activities_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Activities”.', max_length=60, verbose_name='activities list heading'),
        ),
        migrations.AddField(
            model_name='project',
            name='photographs_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Photographs”.', max_length=60, verbose_name='photographs heading'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_projects_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Sub-projects”.', max_length=60, verbose_name='sub-projects list heading'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='about_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “About”.', max_length=60, verbose_name='description heading'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='activities_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Activities”.', max_length=60, verbose_name='activities list heading'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='photographs_heading',
            field=models.CharField(blank=True, help_text='Shown on the public website. Leave blank for “Photographs”.', max_length=60, verbose_name='photographs heading'),
        ),
    ]
