# Generated by Django 6.1.1 on 2026-09-10 06:03

import django.db.models.deletion
import updates.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(db_index=True, help_text='The Monday of the reporting week.', unique=True, verbose_name='week beginning')),
                ('end_date', models.DateField(help_text='The Friday of the reporting week.', verbose_name='week ending')),
                ('theme', models.CharField(blank=True, help_text='Optional. What the week was mainly about, for the convocation slide - e.g. SGLGB assessment of the second district.', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open for contributions'), ('FOR_REVIEW', "For the Chief's review"), ('REVIEWED', 'Reviewed'), ('PUBLISHED', 'Published')], db_index=True, default='OPEN', max_length=20)),
                ('convocation_date', models.DateField(blank=True, help_text='The Monday the week is presented. Left blank, this is the Monday after the reporting week.', null=True)),
                ('chief_remarks', models.TextField(blank=True, help_text='Shown on the convocation view above the accomplishments.', verbose_name="Division Chief's remarks")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Publishes the entries, photographs and POPS Plan figures that are themselves marked for public release. Nothing else leaves the system.', verbose_name='Publish the division summary to the public website')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'reporting period',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='PopsPlanUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment', models.CharField(help_text='The POPS Plan commitment or indicator being reported on.', max_length=255)),
                ('target', models.PositiveIntegerField(default=0, help_text='What was due this period, in whatever unit the plan uses.')),
                ('accomplished', models.PositiveIntegerField(default=0, help_text='What the Division delivered against it.')),
                ('remarks', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='Cleared for the public website')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pops_updates', to='updates.reportingperiod')),
            ],
            options={
                'verbose_name': 'POPS Plan update',
                'verbose_name_plural': 'POPS Plan updates',
                'ordering': ('commitment',),
            },
        ),
        migrations.CreateModel(
            name='DivisionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ACTIVITY', 'Activity'), ('INCOMING', 'Incoming communication'), ('OUTGOING', 'Outgoing communication'), ('TECHNICAL_ASSISTANCE', 'Technical assistance'), ('DELIVERABLE', 'Report / deliverable'), ('POPS_PLAN', 'POPS Plan accomplishment'), ('OTHER', 'Other accomplishment')], db_index=True, default='ACTIVITY', max_length=25)),
                ('activity_type', models.CharField(choices=[('CONDUCTED', 'Conducted'), ('FACILITATED', 'Facilitated'), ('PARTICIPATED', 'Participated in'), ('ATTENDED', 'Attended'), ('MEETING', 'Meeting / coordination'), ('TRAINING', 'Training / seminar'), ('NA', 'Not an activity')], db_index=True, default='NA', help_text="How the Division took part. Leave as 'Not an activity' for communications and deliverables.", max_length=15)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('ONGOING', 'Ongoing'), ('PENDING', 'Pending'), ('UPCOMING', 'Upcoming')], db_index=True, default='COMPLETED', max_length=15)),
                ('narrative', models.TextField(blank=True, help_text='What the Division did, and what came of it.', verbose_name='what was accomplished')),
                ('remarks', models.TextField(blank=True, help_text='Follow-through, issues met, or why the work is still open.')),
                ('activity_date', models.DateField(db_index=True, help_text='The date it happened, or is set to happen.', verbose_name='date')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for a single-day item.', null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('personnel_involved', models.CharField(blank=True, help_text='Others who took part, separated by commas.', max_length=255, verbose_name='assigned personnel / contributors')),
                ('partner', models.CharField(blank=True, max_length=255, verbose_name='partner office or agency')),
                ('reference_number', models.CharField(blank=True, help_text='Control or reference number, for communications and reports.', max_length=100)),
                ('counterpart', models.CharField(blank=True, help_text='Who the communication was received from, or sent to.', max_length=255, verbose_name='from / to')),
                ('is_major', models.BooleanField(db_index=True, default=False, help_text='Selected by the Division Chief as a major accomplishment.', verbose_name='Present at the Monday convocation')),
                ('convocation_order', models.PositiveIntegerField(default=0, help_text='Lowest first. Leave at zero to order by date.', verbose_name='order at the convocation')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Appears publicly once the whole week is published. Leave unticked for anything internal.', verbose_name='Cleared for the public website')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='encoded by')),
                ('focal_person', models.ForeignKey(blank=True, help_text='The staff member who can answer for this item. Recorded for documentation, not for performance measurement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='focal person')),
                ('lgu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_updates', to='lgus.lgu', verbose_name='LGU concerned')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
                ('period', models.ForeignKey(help_text='The division week this belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='updates.reportingperiod', verbose_name='reporting period')),
            ],
            options={
                'verbose_name': 'division update',
                'ordering': ('-activity_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='UpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PHOTO', 'Photo documentation'), ('DOCUMENT', 'Supporting document')], db_index=True, default='PHOTO', max_length=10)),
                ('file', models.FileField(upload_to=updates.models.attachment_path)),
                ('caption', models.CharField(blank=True, help_text='What the photograph shows, or what the document is.', max_length=255)),
                ('is_public', models.BooleanField(default=False, help_text='Photographs of the Division at work; never internal papers.', verbose_name='Cleared for the public website')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='updates.divisionupdate')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attachment',
                'ordering': ('kind', 'uploaded_at'),
            },
        ),
        migrations.CreateModel(
            name='WayForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='way forward')),
                ('detail', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, help_text='When the Division expects to have done it.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=15)),
                ('is_public', models.BooleanField(default=False, verbose_name='Cleared for the public website')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ways_forward', to='updates.reportingperiod')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'way forward',
                'verbose_name_plural': 'ways forward',
                'ordering': ('target_date', 'description'),
            },
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['status', '-start_date'], name='updates_rep_status_32113d_idx'),
        ),
        migrations.AddIndex(
            model_name='divisionupdate',
            index=models.Index(fields=['period', 'category'], name='updates_div_period__f735f0_idx'),
        ),
        migrations.AddIndex(
            model_name='divisionupdate',
            index=models.Index(fields=['period', 'status'], name='updates_div_period__209cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='divisionupdate',
            index=models.Index(fields=['is_public', '-activity_date'], name='updates_div_is_publ_f10848_idx'),
        ),
    ]
