# Generated by Django 6.1.1 on 2026-09-10 07:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.CharField(choices=[('RECENT_WEEKS', 'The most recent completed weeks'), ('RECENT_MONTHS', 'The most recent completed months'), ('DATE_RANGE', 'A fixed range of dates'), ('ALL', 'Every week the Division has published')], default='RECENT_WEEKS', help_text='Only weeks that have been reviewed and published are ever eligible. This decides which of them are on the site now.', max_length=20, verbose_name='what the public website shows')),
                ('weeks_shown', models.PositiveSmallIntegerField(default=8, help_text='Used when the site shows the most recent completed weeks.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='number of weeks')),
                ('months_shown', models.PositiveSmallIntegerField(default=3, help_text='Used when the site shows recent months. Counts the current month and the ones before it.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='number of months')),
                ('range_start', models.DateField(blank=True, help_text='Used when the site shows a fixed range of dates.', null=True, verbose_name='showing from')),
                ('range_end', models.DateField(blank=True, null=True, verbose_name='showing until')),
                ('include_current_week', models.BooleanField(default=False, help_text='Off by default. A week the Division has not finished is a work in progress, not an accomplishment report.', verbose_name='Also show the week that is still running')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'public disclosure window',
                'verbose_name_plural': 'public disclosure window',
            },
        ),
    ]
