# Generated by Django 6.1.1 on 2026-09-10 09:19

import django.db.models.deletion
import updates.models
from django.db import migrations, models


def set_is_image_from_the_file(apps, schema_editor):
    """
    Fill in `is_image` for evidence filed before the column existed.

    It is derived from the file's own extension, so it can be recovered
    exactly rather than guessed from the type it was filed under.
    """
    Attachment = apps.get_model("updates", "UpdateAttachment")
    images = ("jpg", "jpeg", "png", "webp", "gif")
    for attachment in Attachment.objects.exclude(file=""):
        name = attachment.file.name or ""
        extension = name.rsplit(".", 1)[-1].lower() if "." in name else ""
        if extension in images:
            Attachment.objects.filter(pk=attachment.pk).update(is_image=True)


class MigrationOperations:
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_publicdisclosure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateattachment',
            options={'ordering': ('mov_type', 'uploaded_at'), 'verbose_name': 'means of verification', 'verbose_name_plural': 'means of verification'},
        ),
        # A rename rather than a drop-and-add: `kind` already held PHOTO or
        # DOCUMENT, which are both valid `mov_type` values, so any evidence
        # already filed keeps its type instead of silently resetting.
        migrations.RenameField(
            model_name='updateattachment',
            old_name='kind',
            new_name='mov_type',
        ),
        migrations.AddField(
            model_name='updateattachment',
            name='is_image',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='updateattachment',
            name='mov_type',
            field=models.CharField(choices=[('PHOTO', 'Photograph of the activity'), ('DOCUMENT', 'Official document or issuance'), ('REPORT', 'Report or accomplishment record'), ('CERTIFICATE', 'Certificate'), ('ATTENDANCE', 'Attendance sheet'), ('COMMUNICATION', 'Letter or communication'), ('OTHER', 'Other supporting file')], db_index=True, default='PHOTO', help_text='What this file is, for the record and for the presentation.', max_length=20, verbose_name='type of evidence'),
        ),
        migrations.AlterField(
            model_name='updateattachment',
            name='caption',
            field=models.CharField(blank=True, help_text='What the photograph shows, or what the document is - read out beside the accomplishment at the convocation.', max_length=255, verbose_name='what it shows'),
        ),
        migrations.AlterField(
            model_name='updateattachment',
            name='file',
            field=models.FileField(help_text='JPG, PNG or WebP for photographs; PDF, Word, Excel, PowerPoint, CSV or text for documents.', upload_to=updates.models.attachment_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='updateattachment',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Evidence of the Division at work; never internal papers.', verbose_name='Cleared for the public website'),
        ),
        migrations.AlterField(
            model_name='updateattachment',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='updates.divisionupdate', verbose_name='accomplishment or activity'),
        ),
        migrations.RunPython(
            set_is_image_from_the_file, migrations.RunPython.noop
        ),
    ]
