# Generated by Django 6.1.1 on 2026-09-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_alter_updateattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateattachment',
            options={'ordering': ('-is_image', 'mov_type', 'uploaded_at'), 'verbose_name': 'means of verification', 'verbose_name_plural': 'means of verification'},
        ),
    ]
