# Generated by Django 6.1.1 on 2026-09-07 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('REVIEW', 'Awaiting review'), ('OVERDUE', 'Overdue'), ('PUBLICATION', 'Awaiting publication'), ('ASSIGNMENT', 'Assigned to you'), ('ACCOUNT', 'Account'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('ACTION', 'Needs action'), ('URGENT', 'Urgent')], default='INFO', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('url', models.CharField(blank=True, help_text='Where the recipient should go to act.', max_length=255)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Identifies the underlying condition, so a standing issue is not re-notified on every run.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx'), models.Index(fields=['recipient', 'dedupe_key'], name='notificatio_recipie_7d431d_idx')],
            },
        ),
    ]
